### ISSUE TITLE
Add "loaded" class to make transitions easier

### ISSUE THREAD

**Issue by talohana** [talohana/angular-dark-mode#1]
Most of the time people would want to use css transition when changing between light and dark modes.

In order to disable the first transition when the page loads `no-flash.js` is not enough and we need to add some class to flag when DarkModeService finished its' setup.

This way we can add transitioning with:
```css
body.dark-mode-loaded {
  transition: all 0.3s linear;
}
```

**Comment by talohana** [comment]
This is redundant since it can be resolved with css only:
```css
body.dark-mode,
body.light-mode {
    transition: all 0.3s linear;
}
```
